# Generated by Django 6.0.5 on 2026-05-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentations', to='programs.program'),
        ),
    ]
