# Generated by Django 6.0.5 on 2026-06-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_documentation_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documentations/'),
        ),
    ]
