# Generated by Django 6.0.5 on 2026-07-10 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_replaced_user_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF_LAPANGAN', 'Staff Lapangan'), ('MANAGER', 'Manager'), ('STAFF_OPERATIONAL', 'Staff Operational'), ('PENERIMA_MANFAAT', 'Penerima Manfaat')], default='PENERIMA_MANFAAT', max_length=50),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('UPDATE', 'Update Data'), ('DELETE', 'Delete Data'), ('CREATE', 'Create Data')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
